Search movies by title
mehtapparkinson/java-group-project pull request #12
Opened 2024-09-26 15:19 UTC by mobolajii

2024-09-29 14:17 UTC, laila-sb commented
As discussed in slack the two tables need to be merged into one, as team decided to go forward with one table

2024-09-29 15:23 UTC, mehtapparkinson requested changes
when movie name exists in the DB, it returns the existing movie successfully. However, when searched for nonexistent movie it only logs "movie not found" in the backend. I would suggest returning a response entity with 404 and a not found message

2024-10-01 22:36 UTC, mehtapparkinson commented on README.md
> +# java-group-project
is it possible to take this file out of the PR?

2024-10-01 22:37 UTC, mehtapparkinson commented on src/main/java/com/cfg_java_team_jason/java_group_project/controller/MovieController.java
> +    public List<Movie> getAllMovies(){
getAll movies seems to be reverted to previous version here, can we undo that?

2024-10-01 22:41 UTC, mehtapparkinson requested changes
It seems like there was an issue when you were pulling the changes from development into your branch, which caused a lot of deletions. Could you review and undo those changes to ensure everything is correctly synced with development?

2024-10-03 09:44 UTC, closed without merging